(in-package :cl-prada)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(def-prada-domain :blocks
    ((action grab 1)
     (action puton 1)
     (primitive table 1)
     (primitive block 1)
     (primitive ball 1)
     (primitive on 2)
     (primitive inhand 1)
     (primitive upright 1)
     (primitive out 1)
     (primitive size 1 :value-type :integers)

     (conjunction clear 1 :<- (not (on ?y ?x)) :all ?y)
     (conjunction inhandnil 0 :<- (not (inhand ?x)) :all ?x)

     (transclosure above 2 :<- on)

     (conjunction aboveNoTable 2 :<- (and (above ?x ?y)
                                          (not (table ?y))))

     (count height 1 :<- (aboveNoTable ?x ?y) :num ?y)
     (sum sum_height 0 :<- (height ?x)))

  ;; rules
  ((action (default)
           ()
           ((0.5 :no-change)
            (0.5 :noise)))

   (action (puton ?x)
           (and (block ?x) (clear ?x) (inhand ?y))
           ((0.71 (and (on ?y ?x)
                       (upright ?y)
                       (not (inhand ?y))))
            (0.29 :noise)))

   (action (grab ?x)
           (and (on ?x ?y) (upright ?x) (upright ?y) (inhandnil) (not (table ?y)))
           ((0.666 (and (inhand ?x)
                        (not (on ?x ?y))
                        (not (upright ?x))))
            (0.334 :noise)))

   (action (grab ?x)
           (and (table ?y)
                (clear ?x)
                (on ?x ?y)
                (inhandnil))
           ((1 (and (inhand ?x)
                    (not (on ?x ?y))
                    (not (upright ?x))))
            (0 :noise))))

  ;; world-state
  ((ON ball2 ball4) (ON ball1 table1) (ON block1 table1) (ON block2 table1) (ON block3 table1)
   (ON block4 table1)
   (ON ball3 table1) (ON ball4 table1) (UPRIGHT ball1) (UPRIGHT ball2) (UPRIGHT block2)
   (UPRIGHT block3) (UPRIGHT block4) (UPRIGHT ball3) (UPRIGHT ball4) (TABLE table1)
   (BLOCK block1) (BLOCK block2) (BLOCK block3) (BLOCK block4) (BALL ball1) (BALL ball2)
   (BALL ball3) (BALL ball4) (= (SIZE ball1) 1) (= (SIZE ball2) 2) (= (SIZE block1) 2)
   (= (SIZE block2) 2) (= (SIZE block3) 1) (= (SIZE block4) 1) (= (SIZE ball3) 1)
   (= (SIZE ball4) 2) (= (SIZE table1) 4))

  )


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; learning
(defparameter *learn-data*
  (list
   ;; t=0
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (ON V65 V60)
                                              (ON V66 V60) (ON V67 V60)
                                              (ON V68 V60) (ON V69 V68)
                                              (ON V70 V69) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V67) (UPRIGHT V68)
                                              (UPRIGHT V69) (UPRIGHT V70)
                                              (CLEAR V65) (CLEAR V66)
                                              (CLEAR V67) (CLEAR V70)
                                              (INHANDNIL . ())) :action '(GRAB
                                                                          V65))
   ;; t=1
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (INHAND V65)
                                              (ON V66 V60) (ON V67 V60)
                                              (ON V68 V60) (ON V69 V68)
                                              (ON V70 V69) (UPRIGHT V60)
                                              (UPRIGHT V66) (UPRIGHT V67)
                                              (UPRIGHT V68) (UPRIGHT V69)
                                              (UPRIGHT V70) (CLEAR V65)
                                              (CLEAR V66) (CLEAR V67)
                                              (CLEAR V70)) :action '(PUTON
                                                                     V70))
   ;; t=2
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (ON V66 V60)
                                              (ON V67 V60) (ON V68 V60)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V67) (UPRIGHT V68)
                                              (UPRIGHT V69) (UPRIGHT V70)
                                              (CLEAR V65) (CLEAR V66)
                                              (CLEAR V67) (INHANDNIL . ())) :action '(GRAB
                                                                                      V67))
   ;; t=3
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (INHAND V67)
                                              (ON V66 V60) (ON V68 V60)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V68) (UPRIGHT V69)
                                              (UPRIGHT V70) (CLEAR V65)
                                              (CLEAR V66) (CLEAR V67)) :action '(PUTON
                                                                                 V65))
   ;; t=4
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (ON V66 V60)
                                              (ON V68 V60) (ON V67 V65)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V67) (UPRIGHT V68)
                                              (UPRIGHT V69) (UPRIGHT V70)
                                              (CLEAR V66) (CLEAR V67)
                                              (INHANDNIL . ())) :action '(GRAB
                                                                          V66))
   ;; t=5
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (INHAND V66)
                                              (ON V68 V60) (ON V67 V65)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V67)
                                              (UPRIGHT V68) (UPRIGHT V69)
                                              (UPRIGHT V70) (CLEAR V66)
                                              (CLEAR V67)) :action '(PUTON
                                                                     V67))
   ;; t=6
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (ON V68 V60)
                                              (ON V67 V65) (ON V66 V67)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V67) (UPRIGHT V68)
                                              (UPRIGHT V69) (UPRIGHT V70)
                                              (CLEAR V66) (INHANDNIL . ())) :action '(GRAB
                                                                                      V66))
   ;; t=7
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (INHAND V66)
                                              (ON V68 V60) (ON V67 V65)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V67)
                                              (UPRIGHT V68) (UPRIGHT V69)
                                              (UPRIGHT V70) (CLEAR V66)
                                              (CLEAR V67)) :action '(PUTON
                                                                     V67))
   ;; t=8
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (ON V68 V60)
                                              (ON V67 V65) (ON V66 V67)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V67) (UPRIGHT V68)
                                              (UPRIGHT V69) (UPRIGHT V70)
                                              (CLEAR V66) (INHANDNIL . ())) :action '(GRAB
                                                                                      V66))
   ;; t=9
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (INHAND V66)
                                              (ON V68 V60) (ON V67 V65)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V67)
                                              (UPRIGHT V68) (UPRIGHT V69)
                                              (UPRIGHT V70) (CLEAR V66)
                                              (CLEAR V67)) :action '(PUTON
                                                                     V67))
   ;; t=10
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (ON V68 V60)
                                              (ON V67 V65) (ON V66 V67)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V67) (UPRIGHT V68)
                                              (UPRIGHT V69) (UPRIGHT V70)
                                              (CLEAR V66) (INHANDNIL . ())) :action '(GRAB
                                                                                      V66))
   ;; t=11
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (INHAND V66)
                                              (ON V68 V60) (ON V67 V65)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V67)
                                              (UPRIGHT V68) (UPRIGHT V69)
                                              (UPRIGHT V70) (CLEAR V66)
                                              (CLEAR V67)) :action '(PUTON
                                                                     V67))
   ;; t=12
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (ON V68 V60)
                                              (ON V67 V65) (ON V66 V67)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V67) (UPRIGHT V68)
                                              (UPRIGHT V69) (UPRIGHT V70)
                                              (CLEAR V66) (INHANDNIL . ())) :action '(GRAB
                                                                                      V65))
   ;; t=13
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (INHAND V65)
                                              (ON V66 V60) (ON V67 V60)
                                              (ON V68 V60) (ON V69 V68)
                                              (ON V70 V69) (UPRIGHT V60)
                                              (UPRIGHT V67) (UPRIGHT V68)
                                              (UPRIGHT V69) (UPRIGHT V70)
                                              (CLEAR V65) (CLEAR V66)
                                              (CLEAR V67) (CLEAR V70)) :action '(PUTON
                                                                                 V67))
   ;; t=14
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (ON V66 V60)
                                              (ON V67 V60) (ON V68 V60)
                                              (ON V65 V67) (ON V69 V68)
                                              (ON V70 V69) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V67) (UPRIGHT V68)
                                              (UPRIGHT V69) (UPRIGHT V70)
                                              (CLEAR V65) (CLEAR V66)
                                              (CLEAR V70) (INHANDNIL . ())) :action '(GRAB
                                                                                      V65))
   ;; t=15
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (INHAND V65)
                                              (ON V66 V60) (ON V67 V60)
                                              (ON V68 V60) (ON V69 V68)
                                              (ON V70 V69) (UPRIGHT V60)
                                              (UPRIGHT V66) (UPRIGHT V67)
                                              (UPRIGHT V68) (UPRIGHT V69)
                                              (UPRIGHT V70) (CLEAR V65)
                                              (CLEAR V66) (CLEAR V67)
                                              (CLEAR V70)) :action '(PUTON
                                                                     V66))
   ;; t=16
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (ON V66 V60)
                                              (ON V67 V60) (ON V68 V60)
                                              (ON V65 V66) (ON V69 V68)
                                              (ON V70 V69) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V67) (UPRIGHT V68)
                                              (UPRIGHT V69) (UPRIGHT V70)
                                              (CLEAR V65) (CLEAR V67)
                                              (CLEAR V70) (INHANDNIL . ())) :action '(GRAB
                                                                                      V65))
   ;; t=17
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (INHAND V65)
                                              (ON V66 V60) (ON V67 V60)
                                              (ON V68 V60) (ON V69 V68)
                                              (ON V70 V69) (UPRIGHT V60)
                                              (UPRIGHT V66) (UPRIGHT V68)
                                              (UPRIGHT V69) (UPRIGHT V70)
                                              (CLEAR V65) (CLEAR V66)
                                              (CLEAR V67) (CLEAR V70)) :action '(PUTON
                                                                                 V70))
   ;; t=18
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (ON V66 V60)
                                              (ON V67 V60) (ON V68 V60)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V67) (UPRIGHT V68)
                                              (UPRIGHT V69) (UPRIGHT V70)
                                              (CLEAR V65) (CLEAR V66)
                                              (CLEAR V67) (INHANDNIL . ())) :action '(GRAB
                                                                                      V67))
   ;; t=19
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (INHAND V67)
                                              (ON V66 V60) (ON V68 V60)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V68) (UPRIGHT V69)
                                              (UPRIGHT V70) (CLEAR V65)
                                              (CLEAR V66) (CLEAR V67)) :action '(PUTON
                                                                                 V66))
   ;; t=20
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (ON V66 V60)
                                              (ON V68 V60) (ON V67 V66)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V67) (UPRIGHT V68)
                                              (UPRIGHT V69) (UPRIGHT V70)
                                              (CLEAR V65) (CLEAR V67)
                                              (INHANDNIL . ())) :action '(GRAB
                                                                          V67))
   ;; t=21
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (INHAND V67)
                                              (ON V66 V60) (ON V68 V60)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V68) (UPRIGHT V69)
                                              (UPRIGHT V70) (CLEAR V65)
                                              (CLEAR V66) (CLEAR V67)) :action '(PUTON
                                                                                 V66))
   ;; t=22
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (ON V66 V60)
                                              (ON V68 V60) (ON V67 V66)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V67) (UPRIGHT V68)
                                              (UPRIGHT V69) (UPRIGHT V70)
                                              (CLEAR V65) (CLEAR V67)
                                              (INHANDNIL . ())) :action '(GRAB
                                                                          V67))
   ;; t=23
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (INHAND V67)
                                              (ON V66 V60) (ON V68 V60)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V68) (UPRIGHT V69)
                                              (UPRIGHT V70) (CLEAR V65)
                                              (CLEAR V66) (CLEAR V67)) :action '(PUTON
                                                                                 V65))
   ;; t=24
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (ON V66 V60)
                                              (ON V68 V60) (ON V67 V65)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V67) (UPRIGHT V68)
                                              (UPRIGHT V69) (UPRIGHT V70)
                                              (CLEAR V66) (CLEAR V67)
                                              (INHANDNIL . ())) :action '(GRAB
                                                                          V66))
   ;; t=25
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (INHAND V66)
                                              (ON V68 V60) (ON V67 V65)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V67)
                                              (UPRIGHT V68) (UPRIGHT V69)
                                              (UPRIGHT V70) (CLEAR V66)
                                              (CLEAR V67)) :action '(PUTON
                                                                     V67))
   ;; t=26
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (ON V68 V60)
                                              (ON V67 V65) (ON V66 V67)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V67) (UPRIGHT V68)
                                              (UPRIGHT V69) (UPRIGHT V70)
                                              (CLEAR V66) (INHANDNIL . ())) :action '(GRAB
                                                                                      V66))
   ;; t=27
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (INHAND V66)
                                              (ON V68 V60) (ON V67 V65)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V67)
                                              (UPRIGHT V68) (UPRIGHT V69)
                                              (UPRIGHT V70) (CLEAR V66)
                                              (CLEAR V67)) :action '(PUTON
                                                                     V67))
   ;; t=28
   (make-instance 'prada-learn-state :world '((TABLE V60) (BLOCK V65)
                                              (BLOCK V66) (BLOCK V67)
                                              (BLOCK V68) (BLOCK V69)
                                              (BLOCK V70) (= (SIZE V60) 4)
                                              (= (SIZE V65) 3)
                                              (= (SIZE V66) 3)
                                              (= (SIZE V67) 3)
                                              (= (SIZE V68) 3)
                                              (= (SIZE V69) 3)
                                              (= (SIZE V70) 3) (ON V68 V60)
                                              (ON V67 V65) (ON V66 V67)
                                              (ON V69 V68) (ON V70 V69)
                                              (ON V65 V70) (UPRIGHT V60)
                                              (UPRIGHT V65) (UPRIGHT V66)
                                              (UPRIGHT V67) (UPRIGHT V68)
                                              (UPRIGHT V69) (UPRIGHT V70)
                                              (CLEAR V66) (INHANDNIL . ())) :action '(GRAB
                                                                                      V66))))

;;;; vien's paper
(defparameter *obs-learn-data*
  (list
   (make-instance 'prada-learn-state
                  :world '((table t1) (box b1) (on b1 t1) (closed b1)
                            (ucblock b2) (ucexist b2))
                  :action '(open b1))
   (make-instance 'prada-learn-state
                  :world '((table t1) (box b1) (block b2) (on b1 t1) (contains b1 b2)
                           (exist b2)))))

(def-prada-domain :obs
    ;; just need the symbol definitions here
    ((action open 1)

     (primitive table 1)
     (primitive block 1)
     (primitive on 2)
     (primitive box 1)
     (primitive closed 1)
     (primitive contains 2)

     (primitive ucblock 1)
     (primitive ucexist 1)
     (primitive exist 1))
  ;; rules
  ()
  ;; world-state
  ())


;;;;
;; for CPL

(defparameter *cpl-learn-data*
  (list
   (make-instance 'prada-learn-state
                  :world '()
                  :action '())))
(def-prada-domain :cpl
    ;; just need the symbol definitions here
    ((action grab 1)

     (primitive size 1 :value-type :integers))
  ;; rules
  ()
  ;; world-state
  ())


;; goal: rules like
;; grasp ?x
;; pre: (reachable-left ?x) ^ (spatula ?x)
;; outcomes: 0.6 (in-left-gripper ?x) ^ ¬(reachable-left ?x)
